### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by frkngksl** [CCob/SweetPotato#8]
Hi,

Thanks for the latest update about EfsPotato. After the merge commit, I started to get following error:

```
Error CS2001 Source file 'C:\Users\testMachine\Desktop\SweetPotato\NtApiDotNet\Win32\Rpc\Transport\RpcNamedPipeTransport.cs' could not be found.
```

**Comment by CCob** [comment]
Can you try the latest commit?  A few other changes have now taken place.

**Comment by frkngksl** [comment]
Thanks, it compiles now :)
